services:
  chitai:
    image: ghcr.io/taketwo/chitai:latest
    build:
      context: ..
      dockerfile: docker/Dockerfile
    pull_policy: always
    restart: unless-stopped
    ports:
      - "8000:8000"
    volumes:
      - ../data:/app/data
    environment:
      - CHITAI_CERT_DIR=/app/data/certs
    profiles:
      - prod

  chitai-dev:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ../data:/app/data
      - ..:/app
    environment:
      - UV_LINK_MODE=copy
      - UV_PROJECT_ENVIRONMENT=/opt/venv
      - CHITAI_RELOAD=true
      - CHITAI_CERT_DIR=/app/data/certs
    profiles:
      - dev

  watchtower:
    image: containrrr/watchtower
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: --interval 300 --cleanup
    profiles:
      - prod
